### ISSUE TITLE
Improve Prettier config

### ISSUE THREAD

**Issue by mi544** [BootcampersCollective/Coders-Workshop#111]
For arrow functions, following best practices, there should always be parentheses included around an argument.
Consider changing `"arrowParens": "avoid"` in `.prettierrc`

**Comment by mi544** [comment]
On it.

**Comment by mi544** [comment]
Changed the `.prettierrc` according to [best practices](https://prettier.io/docs/en/options.html#arrow-function-parentheses) 

`At first glance, avoiding parentheses may look like a better choice because of less visual noise. However, when Prettier removes parentheses, it becomes harder to add type annotations, extra arguments or default values as well as making other changes. Consistent use of parentheses provides a better developer experience when editing real codebases, which justifies the default value for the option.`

PR: #112

**Comment by bry-an** [comment]
Totally agree, I'm a fan of arrow parens. Thanks, Maks!
