### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by mi544** [BootcampersCollective/Coders-Workshop#122]
Please rename `master` to `main`.

To do this easily, run these two commands:
```bash
git push origin master:main
git push origin :master
```

**Comment by mi544** [comment]
You may need to change the default branch to `main` once it is created since GitHub will probably not let you delete `master` otherwise.

**Comment by mi544** [comment]
@bry-an

**Comment by bry-an** [comment]
Thanks for the suggestion @mi544. Our default branch is now `main`!
