### ISSUE TITLE
Attribute license per contributor

### ISSUE THREAD

**Issue by MartinRosenberg** [BootcampersCollective/Coders-Workshop#66]
The current license attributes copyright for everything to @andy-young. While he totally deserves the credit for running the show, I wonder if that can be adjusted. Licensing is complicated, so I'm not sure how to go about it.

**Comment by iatenine** [comment]
Why not simply use a permissive license such as MIT?

**Comment by MartinRosenberg** [comment]
I haven't been involved with Coders Workshop in a while, but my reasoning at the time likely would've been twofold:

1. The way the MIT license is written grants copyright to a specific individual or group, which is why the license as-is grants copyright over the whole repo to @andy-young. But the copyrights should belong to the individual contributors. I'm not sure if it's possible to modify the license to grant copyright on a per-directory basis, but that seems more hassle than having separate licenses.
2. Though MIT seems like a reasonable default, it's possible certain contributors would prefer their code be licensed differently, e.g. GPL 3. That is only feasible with separate licenses.

I did discuss this at the time with @andy-young and @bry-an, if I recall correctly, but we never got around to making any changes.
