### ISSUE TITLE
Put solutions with challenges?

### ISSUE THREAD

**Issue by MartinRosenberg** [BootcampersCollective/Coders-Workshop#68]
Should solutions to challenges be put in `solutions` folders alongside the challenges themselves?

## Pros

* Easy to navigate between the challenge itself and the solution(s) to it
* Easy to navigate between different solutions to compare approaches

## Cons

* Harder to track contributions per developer

**Comment by iatenine** [comment]
I would say no personally but would recommend providing a test script people can use to check if their solutions function properly

**Comment by MartinRosenberg** [comment]
This was discussed at the time with @andy-young and @bry-an and we did intend to follow through, but changes continued to be merged in that broke this pattern and made it difficult to create a PR, so it was never completed.

The thought process was that the purpose of this meetup is to be a workshop, not a showcase, and structuring the repo so that various solutions and tests are all easily accessible from the challenge, instead of needing to dig around to find who contributed solutions to which challenge, makes the content much easier to learn from.

This approach does, however, conflict with #66 unless someone has a good idea how to structure per-contributor licenses without contributor directories.

**Comment by iatenine** [comment]
While I don't have any easy solution for the licensing issues, is that to say that I _could_ contribute test scripts to certain challenges if I'm not concerned with the licensing itself?

**Comment by MartinRosenberg** [comment]
Oh, absolutely! People, including myself, have been contributing to this repository as long as it's been around. It's just that the current LICENSE file marks everything as being "Copyright (c) 2019 Andy Young" and MIT licensed. If that doesn't bother you, or you've got an interim solution for your own contributions, go for it!

**Comment by iatenine** [comment]
What I'm hearing is that if I contribute a file that just _happens_ to have comments along the lines of "Jack is so cool. I wish I was him" then, legally speaking, Andy was the one who said those words...

OK, great! Keep an eye out for some PRs in the near future to the challenges which can realistically have such a test written

**Comment by MartinRosenberg** [comment]
Look, I have no attachment to this anymore, I was just letting you know what the discussion was at the time because it wasn't all recorded here previously and you took an interest. I wasn't aware at the time that your interest was a cover for a vendetta, especially given I don't actually know you.

**Comment by MartinRosenberg** [comment]
Look, I have no attachment to this anymore, I was just letting you know what the discussion was at the time because it wasn't all recorded here previously and you took an interest. I'm honestly not sure what your issue is with me.
